### ISSUE TITLE
Vuejs component cannot receive data

### ISSUE THREAD

**Issue by neutt22** [icebob/vue-websocket#11]
What makes `line 751` work while `line 757` won't?

![image](https://user-images.githubusercontent.com/8733987/44198337-baacd500-a173-11e8-80d1-8e81239a398c.png)

**Comment by sam3d** [comment]
When you say it's not working, are you getting an error?

**Comment by neutt22** [comment]
@sam3d No, not all. Anyway, I just decided to keep it that way and remove the `socket` object.
