### ISSUE TITLE
Is it possible to use multiple prefixes in one Vue component?

### ISSUE THREAD

**Issue by ianfiske** [icebob/vue-websocket#5]
If I have a component which has a `socket` property as documented in the vue-websocket's README, is there a way to subscribe to listen on multiple prefixes?  The documentation only shows how to listen on a single prefix in a component.  Thanks!

**Comment by sam3d** [comment]
Is this still an issue with which you need help, @ianfiske?

**Comment by ianfiske** [comment]
No, but thanks for checking @sam3d.

**Comment by brhx** [comment]
Don't mention it, thanks for following up!
